apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: app-deployment
          image: devsecopscoereg.azurecr.io/nodeapp:1.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
          ports:
            - containerPort: 3002
      imagePullSecrets:
        - name: appacr    
        

